/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTwatterIndexRouteImport } from './routes/_app/twatter/index'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRegexesIndexRouteImport } from './routes/_app/regexes/index'
import { Route as AppPresetsIndexRouteImport } from './routes/_app/presets/index'
import { Route as AppPersonasIndexRouteImport } from './routes/_app/personas/index'
import { Route as AppLorebooksIndexRouteImport } from './routes/_app/lorebooks/index'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppChatsIndexRouteImport } from './routes/_app/chats/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as ChatChatsChatIdIndexRouteImport } from './routes/_chat/chats/$chatId/index'
import { Route as AppToolsToolIdIndexRouteImport } from './routes/_app/tools/$toolId/index'
import { Route as AppRegexesRegexIdIndexRouteImport } from './routes/_app/regexes/$regexId/index'
import { Route as AppPresetsPresetIdIndexRouteImport } from './routes/_app/presets/$presetId/index'
import { Route as AppPersonasPersonaIdIndexRouteImport } from './routes/_app/personas/$personaId/index'
import { Route as AppLorebooksLorebookIdIndexRouteImport } from './routes/_app/lorebooks/$lorebookId/index'
import { Route as AppConnectionsConnectionIdIndexRouteImport } from './routes/_app/connections/$connectionId/index'
import { Route as AppCharactersCharacterIdIndexRouteImport } from './routes/_app/characters/$characterId/index'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents/$agentId/index'

const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTwatterIndexRoute = AppTwatterIndexRouteImport.update({
  id: '/twatter/',
  path: '/twatter/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegexesIndexRoute = AppRegexesIndexRouteImport.update({
  id: '/regexes/',
  path: '/regexes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPresetsIndexRoute = AppPresetsIndexRouteImport.update({
  id: '/presets/',
  path: '/presets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonasIndexRoute = AppPersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLorebooksIndexRoute = AppLorebooksIndexRouteImport.update({
  id: '/lorebooks/',
  path: '/lorebooks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ChatChatsChatIdIndexRoute = ChatChatsChatIdIndexRouteImport.update({
  id: '/chats/$chatId/',
  path: '/chats/$chatId/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const AppToolsToolIdIndexRoute = AppToolsToolIdIndexRouteImport.update({
  id: '/tools/$toolId/',
  path: '/tools/$toolId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegexesRegexIdIndexRoute = AppRegexesRegexIdIndexRouteImport.update({
  id: '/regexes/$regexId/',
  path: '/regexes/$regexId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPresetsPresetIdIndexRoute = AppPresetsPresetIdIndexRouteImport.update({
  id: '/presets/$presetId/',
  path: '/presets/$presetId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonasPersonaIdIndexRoute =
  AppPersonasPersonaIdIndexRouteImport.update({
    id: '/personas/$personaId/',
    path: '/personas/$personaId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLorebooksLorebookIdIndexRoute =
  AppLorebooksLorebookIdIndexRouteImport.update({
    id: '/lorebooks/$lorebookId/',
    path: '/lorebooks/$lorebookId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConnectionsConnectionIdIndexRoute =
  AppConnectionsConnectionIdIndexRouteImport.update({
    id: '/connections/$connectionId/',
    path: '/connections/$connectionId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCharactersCharacterIdIndexRoute =
  AppCharactersCharacterIdIndexRouteImport.update({
    id: '/characters/$characterId/',
    path: '/characters/$characterId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/chats/': typeof AppChatsIndexRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/lorebooks/': typeof AppLorebooksIndexRoute
  '/personas/': typeof AppPersonasIndexRoute
  '/presets/': typeof AppPresetsIndexRoute
  '/regexes/': typeof AppRegexesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/twatter/': typeof AppTwatterIndexRoute
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/characters/$characterId/': typeof AppCharactersCharacterIdIndexRoute
  '/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/lorebooks/$lorebookId/': typeof AppLorebooksLorebookIdIndexRoute
  '/personas/$personaId/': typeof AppPersonasPersonaIdIndexRoute
  '/presets/$presetId/': typeof AppPresetsPresetIdIndexRoute
  '/regexes/$regexId/': typeof AppRegexesRegexIdIndexRoute
  '/tools/$toolId/': typeof AppToolsToolIdIndexRoute
  '/chats/$chatId/': typeof ChatChatsChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/agents': typeof AppAgentsIndexRoute
  '/characters': typeof AppCharactersIndexRoute
  '/chats': typeof AppChatsIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/lorebooks': typeof AppLorebooksIndexRoute
  '/personas': typeof AppPersonasIndexRoute
  '/presets': typeof AppPresetsIndexRoute
  '/regexes': typeof AppRegexesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/twatter': typeof AppTwatterIndexRoute
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdIndexRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdIndexRoute
  '/lorebooks/$lorebookId': typeof AppLorebooksLorebookIdIndexRoute
  '/personas/$personaId': typeof AppPersonasPersonaIdIndexRoute
  '/presets/$presetId': typeof AppPresetsPresetIdIndexRoute
  '/regexes/$regexId': typeof AppRegexesRegexIdIndexRoute
  '/tools/$toolId': typeof AppToolsToolIdIndexRoute
  '/chats/$chatId': typeof ChatChatsChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_chat': typeof ChatRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/lorebooks/': typeof AppLorebooksIndexRoute
  '/_app/personas/': typeof AppPersonasIndexRoute
  '/_app/presets/': typeof AppPresetsIndexRoute
  '/_app/regexes/': typeof AppRegexesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/twatter/': typeof AppTwatterIndexRoute
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/_app/characters/$characterId/': typeof AppCharactersCharacterIdIndexRoute
  '/_app/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/_app/lorebooks/$lorebookId/': typeof AppLorebooksLorebookIdIndexRoute
  '/_app/personas/$personaId/': typeof AppPersonasPersonaIdIndexRoute
  '/_app/presets/$presetId/': typeof AppPresetsPresetIdIndexRoute
  '/_app/regexes/$regexId/': typeof AppRegexesRegexIdIndexRoute
  '/_app/tools/$toolId/': typeof AppToolsToolIdIndexRoute
  '/_chat/chats/$chatId/': typeof ChatChatsChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/'
    | '/characters/'
    | '/chats/'
    | '/connections/'
    | '/lorebooks/'
    | '/personas/'
    | '/presets/'
    | '/regexes/'
    | '/settings/'
    | '/tools/'
    | '/twatter/'
    | '/agents/$agentId/'
    | '/characters/$characterId/'
    | '/connections/$connectionId/'
    | '/lorebooks/$lorebookId/'
    | '/personas/$personaId/'
    | '/presets/$presetId/'
    | '/regexes/$regexId/'
    | '/tools/$toolId/'
    | '/chats/$chatId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/characters'
    | '/chats'
    | '/connections'
    | '/lorebooks'
    | '/personas'
    | '/presets'
    | '/regexes'
    | '/settings'
    | '/tools'
    | '/twatter'
    | '/agents/$agentId'
    | '/characters/$characterId'
    | '/connections/$connectionId'
    | '/lorebooks/$lorebookId'
    | '/personas/$personaId'
    | '/presets/$presetId'
    | '/regexes/$regexId'
    | '/tools/$toolId'
    | '/chats/$chatId'
  id:
    | '__root__'
    | '/_app'
    | '/_chat'
    | '/_app/'
    | '/_app/agents/'
    | '/_app/characters/'
    | '/_app/chats/'
    | '/_app/connections/'
    | '/_app/lorebooks/'
    | '/_app/personas/'
    | '/_app/presets/'
    | '/_app/regexes/'
    | '/_app/settings/'
    | '/_app/tools/'
    | '/_app/twatter/'
    | '/_app/agents/$agentId/'
    | '/_app/characters/$characterId/'
    | '/_app/connections/$connectionId/'
    | '/_app/lorebooks/$lorebookId/'
    | '/_app/personas/$personaId/'
    | '/_app/presets/$presetId/'
    | '/_app/regexes/$regexId/'
    | '/_app/tools/$toolId/'
    | '/_chat/chats/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/twatter/': {
      id: '/_app/twatter/'
      path: '/twatter'
      fullPath: '/twatter/'
      preLoaderRoute: typeof AppTwatterIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/regexes/': {
      id: '/_app/regexes/'
      path: '/regexes'
      fullPath: '/regexes/'
      preLoaderRoute: typeof AppRegexesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/presets/': {
      id: '/_app/presets/'
      path: '/presets'
      fullPath: '/presets/'
      preLoaderRoute: typeof AppPresetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/personas/': {
      id: '/_app/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof AppPersonasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lorebooks/': {
      id: '/_app/lorebooks/'
      path: '/lorebooks'
      fullPath: '/lorebooks/'
      preLoaderRoute: typeof AppLorebooksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_chat/chats/$chatId/': {
      id: '/_chat/chats/$chatId/'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId/'
      preLoaderRoute: typeof ChatChatsChatIdIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/_app/tools/$toolId/': {
      id: '/_app/tools/$toolId/'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId/'
      preLoaderRoute: typeof AppToolsToolIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/regexes/$regexId/': {
      id: '/_app/regexes/$regexId/'
      path: '/regexes/$regexId'
      fullPath: '/regexes/$regexId/'
      preLoaderRoute: typeof AppRegexesRegexIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/presets/$presetId/': {
      id: '/_app/presets/$presetId/'
      path: '/presets/$presetId'
      fullPath: '/presets/$presetId/'
      preLoaderRoute: typeof AppPresetsPresetIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/personas/$personaId/': {
      id: '/_app/personas/$personaId/'
      path: '/personas/$personaId'
      fullPath: '/personas/$personaId/'
      preLoaderRoute: typeof AppPersonasPersonaIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lorebooks/$lorebookId/': {
      id: '/_app/lorebooks/$lorebookId/'
      path: '/lorebooks/$lorebookId'
      fullPath: '/lorebooks/$lorebookId/'
      preLoaderRoute: typeof AppLorebooksLorebookIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connections/$connectionId/': {
      id: '/_app/connections/$connectionId/'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId/'
      preLoaderRoute: typeof AppConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/$characterId/': {
      id: '/_app/characters/$characterId/'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId/'
      preLoaderRoute: typeof AppCharactersCharacterIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppLorebooksIndexRoute: typeof AppLorebooksIndexRoute
  AppPersonasIndexRoute: typeof AppPersonasIndexRoute
  AppPresetsIndexRoute: typeof AppPresetsIndexRoute
  AppRegexesIndexRoute: typeof AppRegexesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppTwatterIndexRoute: typeof AppTwatterIndexRoute
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
  AppCharactersCharacterIdIndexRoute: typeof AppCharactersCharacterIdIndexRoute
  AppConnectionsConnectionIdIndexRoute: typeof AppConnectionsConnectionIdIndexRoute
  AppLorebooksLorebookIdIndexRoute: typeof AppLorebooksLorebookIdIndexRoute
  AppPersonasPersonaIdIndexRoute: typeof AppPersonasPersonaIdIndexRoute
  AppPresetsPresetIdIndexRoute: typeof AppPresetsPresetIdIndexRoute
  AppRegexesRegexIdIndexRoute: typeof AppRegexesRegexIdIndexRoute
  AppToolsToolIdIndexRoute: typeof AppToolsToolIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppLorebooksIndexRoute: AppLorebooksIndexRoute,
  AppPersonasIndexRoute: AppPersonasIndexRoute,
  AppPresetsIndexRoute: AppPresetsIndexRoute,
  AppRegexesIndexRoute: AppRegexesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppTwatterIndexRoute: AppTwatterIndexRoute,
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
  AppCharactersCharacterIdIndexRoute: AppCharactersCharacterIdIndexRoute,
  AppConnectionsConnectionIdIndexRoute: AppConnectionsConnectionIdIndexRoute,
  AppLorebooksLorebookIdIndexRoute: AppLorebooksLorebookIdIndexRoute,
  AppPersonasPersonaIdIndexRoute: AppPersonasPersonaIdIndexRoute,
  AppPresetsPresetIdIndexRoute: AppPresetsPresetIdIndexRoute,
  AppRegexesRegexIdIndexRoute: AppRegexesRegexIdIndexRoute,
  AppToolsToolIdIndexRoute: AppToolsToolIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ChatRouteRouteChildren {
  ChatChatsChatIdIndexRoute: typeof ChatChatsChatIdIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatChatsChatIdIndexRoute: ChatChatsChatIdIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ChatRouteRoute: ChatRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
