/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwatterRouteRouteImport } from './routes/_twatter/route'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as TwatterTwatterIndexRouteImport } from './routes/_twatter/twatter/index'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRegexesIndexRouteImport } from './routes/_app/regexes/index'
import { Route as AppPresetsIndexRouteImport } from './routes/_app/presets/index'
import { Route as AppPersonasIndexRouteImport } from './routes/_app/personas/index'
import { Route as AppLorebooksIndexRouteImport } from './routes/_app/lorebooks/index'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppChatsIndexRouteImport } from './routes/_app/chats/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppActivityIndexRouteImport } from './routes/_app/activity/index'
import { Route as TwatterTwatterSettingsRouteImport } from './routes/_twatter/twatter/settings'
import { Route as TwatterTwatterSearchRouteImport } from './routes/_twatter/twatter/search'
import { Route as TwatterTwatterNotificationsRouteImport } from './routes/_twatter/twatter/notifications'
import { Route as TwatterTwatterProfileIndexRouteImport } from './routes/_twatter/twatter/profile/index'
import { Route as ChatChatsChatIdIndexRouteImport } from './routes/_chat/chats/$chatId/index'
import { Route as AppToolsToolIdIndexRouteImport } from './routes/_app/tools/$toolId/index'
import { Route as AppRegexesRegexIdIndexRouteImport } from './routes/_app/regexes/$regexId/index'
import { Route as AppPresetsPresetIdIndexRouteImport } from './routes/_app/presets/$presetId/index'
import { Route as AppPersonasPersonaIdIndexRouteImport } from './routes/_app/personas/$personaId/index'
import { Route as AppLorebooksLorebookIdIndexRouteImport } from './routes/_app/lorebooks/$lorebookId/index'
import { Route as AppConnectionsConnectionIdIndexRouteImport } from './routes/_app/connections/$connectionId/index'
import { Route as AppCharactersImportIndexRouteImport } from './routes/_app/characters/import/index'
import { Route as AppCharactersCharacterIdIndexRouteImport } from './routes/_app/characters/$characterId/index'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents/$agentId/index'
import { Route as TwatterTwatterProfileAccountIdRouteImport } from './routes/_twatter/twatter/profile/$accountId'
import { Route as AppCharactersImportCardIdIndexRouteImport } from './routes/_app/characters/import/$cardId/index'

const TwatterRouteRoute = TwatterRouteRouteImport.update({
  id: '/_twatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const TwatterTwatterIndexRoute = TwatterTwatterIndexRouteImport.update({
  id: '/twatter/',
  path: '/twatter/',
  getParentRoute: () => TwatterRouteRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegexesIndexRoute = AppRegexesIndexRouteImport.update({
  id: '/regexes/',
  path: '/regexes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPresetsIndexRoute = AppPresetsIndexRouteImport.update({
  id: '/presets/',
  path: '/presets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonasIndexRoute = AppPersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLorebooksIndexRoute = AppLorebooksIndexRouteImport.update({
  id: '/lorebooks/',
  path: '/lorebooks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityIndexRoute = AppActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AppRouteRoute,
} as any)
const TwatterTwatterSettingsRoute = TwatterTwatterSettingsRouteImport.update({
  id: '/twatter/settings',
  path: '/twatter/settings',
  getParentRoute: () => TwatterRouteRoute,
} as any)
const TwatterTwatterSearchRoute = TwatterTwatterSearchRouteImport.update({
  id: '/twatter/search',
  path: '/twatter/search',
  getParentRoute: () => TwatterRouteRoute,
} as any)
const TwatterTwatterNotificationsRoute =
  TwatterTwatterNotificationsRouteImport.update({
    id: '/twatter/notifications',
    path: '/twatter/notifications',
    getParentRoute: () => TwatterRouteRoute,
  } as any)
const TwatterTwatterProfileIndexRoute =
  TwatterTwatterProfileIndexRouteImport.update({
    id: '/twatter/profile/',
    path: '/twatter/profile/',
    getParentRoute: () => TwatterRouteRoute,
  } as any)
const ChatChatsChatIdIndexRoute = ChatChatsChatIdIndexRouteImport.update({
  id: '/chats/$chatId/',
  path: '/chats/$chatId/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const AppToolsToolIdIndexRoute = AppToolsToolIdIndexRouteImport.update({
  id: '/tools/$toolId/',
  path: '/tools/$toolId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRegexesRegexIdIndexRoute = AppRegexesRegexIdIndexRouteImport.update({
  id: '/regexes/$regexId/',
  path: '/regexes/$regexId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPresetsPresetIdIndexRoute = AppPresetsPresetIdIndexRouteImport.update({
  id: '/presets/$presetId/',
  path: '/presets/$presetId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonasPersonaIdIndexRoute =
  AppPersonasPersonaIdIndexRouteImport.update({
    id: '/personas/$personaId/',
    path: '/personas/$personaId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLorebooksLorebookIdIndexRoute =
  AppLorebooksLorebookIdIndexRouteImport.update({
    id: '/lorebooks/$lorebookId/',
    path: '/lorebooks/$lorebookId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppConnectionsConnectionIdIndexRoute =
  AppConnectionsConnectionIdIndexRouteImport.update({
    id: '/connections/$connectionId/',
    path: '/connections/$connectionId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCharactersImportIndexRoute =
  AppCharactersImportIndexRouteImport.update({
    id: '/characters/import/',
    path: '/characters/import/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCharactersCharacterIdIndexRoute =
  AppCharactersCharacterIdIndexRouteImport.update({
    id: '/characters/$characterId/',
    path: '/characters/$characterId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const TwatterTwatterProfileAccountIdRoute =
  TwatterTwatterProfileAccountIdRouteImport.update({
    id: '/twatter/profile/$accountId',
    path: '/twatter/profile/$accountId',
    getParentRoute: () => TwatterRouteRoute,
  } as any)
const AppCharactersImportCardIdIndexRoute =
  AppCharactersImportCardIdIndexRouteImport.update({
    id: '/characters/import/$cardId/',
    path: '/characters/import/$cardId/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/twatter/notifications': typeof TwatterTwatterNotificationsRoute
  '/twatter/search': typeof TwatterTwatterSearchRoute
  '/twatter/settings': typeof TwatterTwatterSettingsRoute
  '/activity/': typeof AppActivityIndexRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/chats/': typeof AppChatsIndexRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/lorebooks/': typeof AppLorebooksIndexRoute
  '/personas/': typeof AppPersonasIndexRoute
  '/presets/': typeof AppPresetsIndexRoute
  '/regexes/': typeof AppRegexesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/twatter/': typeof TwatterTwatterIndexRoute
  '/twatter/profile/$accountId': typeof TwatterTwatterProfileAccountIdRoute
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/characters/$characterId/': typeof AppCharactersCharacterIdIndexRoute
  '/characters/import/': typeof AppCharactersImportIndexRoute
  '/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/lorebooks/$lorebookId/': typeof AppLorebooksLorebookIdIndexRoute
  '/personas/$personaId/': typeof AppPersonasPersonaIdIndexRoute
  '/presets/$presetId/': typeof AppPresetsPresetIdIndexRoute
  '/regexes/$regexId/': typeof AppRegexesRegexIdIndexRoute
  '/tools/$toolId/': typeof AppToolsToolIdIndexRoute
  '/chats/$chatId/': typeof ChatChatsChatIdIndexRoute
  '/twatter/profile/': typeof TwatterTwatterProfileIndexRoute
  '/characters/import/$cardId/': typeof AppCharactersImportCardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/twatter/notifications': typeof TwatterTwatterNotificationsRoute
  '/twatter/search': typeof TwatterTwatterSearchRoute
  '/twatter/settings': typeof TwatterTwatterSettingsRoute
  '/activity': typeof AppActivityIndexRoute
  '/agents': typeof AppAgentsIndexRoute
  '/characters': typeof AppCharactersIndexRoute
  '/chats': typeof AppChatsIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/lorebooks': typeof AppLorebooksIndexRoute
  '/personas': typeof AppPersonasIndexRoute
  '/presets': typeof AppPresetsIndexRoute
  '/regexes': typeof AppRegexesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/twatter': typeof TwatterTwatterIndexRoute
  '/twatter/profile/$accountId': typeof TwatterTwatterProfileAccountIdRoute
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdIndexRoute
  '/characters/import': typeof AppCharactersImportIndexRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdIndexRoute
  '/lorebooks/$lorebookId': typeof AppLorebooksLorebookIdIndexRoute
  '/personas/$personaId': typeof AppPersonasPersonaIdIndexRoute
  '/presets/$presetId': typeof AppPresetsPresetIdIndexRoute
  '/regexes/$regexId': typeof AppRegexesRegexIdIndexRoute
  '/tools/$toolId': typeof AppToolsToolIdIndexRoute
  '/chats/$chatId': typeof ChatChatsChatIdIndexRoute
  '/twatter/profile': typeof TwatterTwatterProfileIndexRoute
  '/characters/import/$cardId': typeof AppCharactersImportCardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_chat': typeof ChatRouteRouteWithChildren
  '/_twatter': typeof TwatterRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_twatter/twatter/notifications': typeof TwatterTwatterNotificationsRoute
  '/_twatter/twatter/search': typeof TwatterTwatterSearchRoute
  '/_twatter/twatter/settings': typeof TwatterTwatterSettingsRoute
  '/_app/activity/': typeof AppActivityIndexRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/lorebooks/': typeof AppLorebooksIndexRoute
  '/_app/personas/': typeof AppPersonasIndexRoute
  '/_app/presets/': typeof AppPresetsIndexRoute
  '/_app/regexes/': typeof AppRegexesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_twatter/twatter/': typeof TwatterTwatterIndexRoute
  '/_twatter/twatter/profile/$accountId': typeof TwatterTwatterProfileAccountIdRoute
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/_app/characters/$characterId/': typeof AppCharactersCharacterIdIndexRoute
  '/_app/characters/import/': typeof AppCharactersImportIndexRoute
  '/_app/connections/$connectionId/': typeof AppConnectionsConnectionIdIndexRoute
  '/_app/lorebooks/$lorebookId/': typeof AppLorebooksLorebookIdIndexRoute
  '/_app/personas/$personaId/': typeof AppPersonasPersonaIdIndexRoute
  '/_app/presets/$presetId/': typeof AppPresetsPresetIdIndexRoute
  '/_app/regexes/$regexId/': typeof AppRegexesRegexIdIndexRoute
  '/_app/tools/$toolId/': typeof AppToolsToolIdIndexRoute
  '/_chat/chats/$chatId/': typeof ChatChatsChatIdIndexRoute
  '/_twatter/twatter/profile/': typeof TwatterTwatterProfileIndexRoute
  '/_app/characters/import/$cardId/': typeof AppCharactersImportCardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/twatter/notifications'
    | '/twatter/search'
    | '/twatter/settings'
    | '/activity/'
    | '/agents/'
    | '/characters/'
    | '/chats/'
    | '/connections/'
    | '/lorebooks/'
    | '/personas/'
    | '/presets/'
    | '/regexes/'
    | '/settings/'
    | '/tools/'
    | '/twatter/'
    | '/twatter/profile/$accountId'
    | '/agents/$agentId/'
    | '/characters/$characterId/'
    | '/characters/import/'
    | '/connections/$connectionId/'
    | '/lorebooks/$lorebookId/'
    | '/personas/$personaId/'
    | '/presets/$presetId/'
    | '/regexes/$regexId/'
    | '/tools/$toolId/'
    | '/chats/$chatId/'
    | '/twatter/profile/'
    | '/characters/import/$cardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/twatter/notifications'
    | '/twatter/search'
    | '/twatter/settings'
    | '/activity'
    | '/agents'
    | '/characters'
    | '/chats'
    | '/connections'
    | '/lorebooks'
    | '/personas'
    | '/presets'
    | '/regexes'
    | '/settings'
    | '/tools'
    | '/twatter'
    | '/twatter/profile/$accountId'
    | '/agents/$agentId'
    | '/characters/$characterId'
    | '/characters/import'
    | '/connections/$connectionId'
    | '/lorebooks/$lorebookId'
    | '/personas/$personaId'
    | '/presets/$presetId'
    | '/regexes/$regexId'
    | '/tools/$toolId'
    | '/chats/$chatId'
    | '/twatter/profile'
    | '/characters/import/$cardId'
  id:
    | '__root__'
    | '/_app'
    | '/_chat'
    | '/_twatter'
    | '/_app/'
    | '/_twatter/twatter/notifications'
    | '/_twatter/twatter/search'
    | '/_twatter/twatter/settings'
    | '/_app/activity/'
    | '/_app/agents/'
    | '/_app/characters/'
    | '/_app/chats/'
    | '/_app/connections/'
    | '/_app/lorebooks/'
    | '/_app/personas/'
    | '/_app/presets/'
    | '/_app/regexes/'
    | '/_app/settings/'
    | '/_app/tools/'
    | '/_twatter/twatter/'
    | '/_twatter/twatter/profile/$accountId'
    | '/_app/agents/$agentId/'
    | '/_app/characters/$characterId/'
    | '/_app/characters/import/'
    | '/_app/connections/$connectionId/'
    | '/_app/lorebooks/$lorebookId/'
    | '/_app/personas/$personaId/'
    | '/_app/presets/$presetId/'
    | '/_app/regexes/$regexId/'
    | '/_app/tools/$toolId/'
    | '/_chat/chats/$chatId/'
    | '/_twatter/twatter/profile/'
    | '/_app/characters/import/$cardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  TwatterRouteRoute: typeof TwatterRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_twatter': {
      id: '/_twatter'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TwatterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_twatter/twatter/': {
      id: '/_twatter/twatter/'
      path: '/twatter'
      fullPath: '/twatter/'
      preLoaderRoute: typeof TwatterTwatterIndexRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/regexes/': {
      id: '/_app/regexes/'
      path: '/regexes'
      fullPath: '/regexes/'
      preLoaderRoute: typeof AppRegexesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/presets/': {
      id: '/_app/presets/'
      path: '/presets'
      fullPath: '/presets/'
      preLoaderRoute: typeof AppPresetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/personas/': {
      id: '/_app/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof AppPersonasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lorebooks/': {
      id: '/_app/lorebooks/'
      path: '/lorebooks'
      fullPath: '/lorebooks/'
      preLoaderRoute: typeof AppLorebooksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/activity/': {
      id: '/_app/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AppActivityIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_twatter/twatter/settings': {
      id: '/_twatter/twatter/settings'
      path: '/twatter/settings'
      fullPath: '/twatter/settings'
      preLoaderRoute: typeof TwatterTwatterSettingsRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_twatter/twatter/search': {
      id: '/_twatter/twatter/search'
      path: '/twatter/search'
      fullPath: '/twatter/search'
      preLoaderRoute: typeof TwatterTwatterSearchRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_twatter/twatter/notifications': {
      id: '/_twatter/twatter/notifications'
      path: '/twatter/notifications'
      fullPath: '/twatter/notifications'
      preLoaderRoute: typeof TwatterTwatterNotificationsRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_twatter/twatter/profile/': {
      id: '/_twatter/twatter/profile/'
      path: '/twatter/profile'
      fullPath: '/twatter/profile/'
      preLoaderRoute: typeof TwatterTwatterProfileIndexRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_chat/chats/$chatId/': {
      id: '/_chat/chats/$chatId/'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId/'
      preLoaderRoute: typeof ChatChatsChatIdIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/_app/tools/$toolId/': {
      id: '/_app/tools/$toolId/'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId/'
      preLoaderRoute: typeof AppToolsToolIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/regexes/$regexId/': {
      id: '/_app/regexes/$regexId/'
      path: '/regexes/$regexId'
      fullPath: '/regexes/$regexId/'
      preLoaderRoute: typeof AppRegexesRegexIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/presets/$presetId/': {
      id: '/_app/presets/$presetId/'
      path: '/presets/$presetId'
      fullPath: '/presets/$presetId/'
      preLoaderRoute: typeof AppPresetsPresetIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/personas/$personaId/': {
      id: '/_app/personas/$personaId/'
      path: '/personas/$personaId'
      fullPath: '/personas/$personaId/'
      preLoaderRoute: typeof AppPersonasPersonaIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lorebooks/$lorebookId/': {
      id: '/_app/lorebooks/$lorebookId/'
      path: '/lorebooks/$lorebookId'
      fullPath: '/lorebooks/$lorebookId/'
      preLoaderRoute: typeof AppLorebooksLorebookIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/connections/$connectionId/': {
      id: '/_app/connections/$connectionId/'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId/'
      preLoaderRoute: typeof AppConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/import/': {
      id: '/_app/characters/import/'
      path: '/characters/import'
      fullPath: '/characters/import/'
      preLoaderRoute: typeof AppCharactersImportIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/$characterId/': {
      id: '/_app/characters/$characterId/'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId/'
      preLoaderRoute: typeof AppCharactersCharacterIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_twatter/twatter/profile/$accountId': {
      id: '/_twatter/twatter/profile/$accountId'
      path: '/twatter/profile/$accountId'
      fullPath: '/twatter/profile/$accountId'
      preLoaderRoute: typeof TwatterTwatterProfileAccountIdRouteImport
      parentRoute: typeof TwatterRouteRoute
    }
    '/_app/characters/import/$cardId/': {
      id: '/_app/characters/import/$cardId/'
      path: '/characters/import/$cardId'
      fullPath: '/characters/import/$cardId/'
      preLoaderRoute: typeof AppCharactersImportCardIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppActivityIndexRoute: typeof AppActivityIndexRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppLorebooksIndexRoute: typeof AppLorebooksIndexRoute
  AppPersonasIndexRoute: typeof AppPersonasIndexRoute
  AppPresetsIndexRoute: typeof AppPresetsIndexRoute
  AppRegexesIndexRoute: typeof AppRegexesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
  AppCharactersCharacterIdIndexRoute: typeof AppCharactersCharacterIdIndexRoute
  AppCharactersImportIndexRoute: typeof AppCharactersImportIndexRoute
  AppConnectionsConnectionIdIndexRoute: typeof AppConnectionsConnectionIdIndexRoute
  AppLorebooksLorebookIdIndexRoute: typeof AppLorebooksLorebookIdIndexRoute
  AppPersonasPersonaIdIndexRoute: typeof AppPersonasPersonaIdIndexRoute
  AppPresetsPresetIdIndexRoute: typeof AppPresetsPresetIdIndexRoute
  AppRegexesRegexIdIndexRoute: typeof AppRegexesRegexIdIndexRoute
  AppToolsToolIdIndexRoute: typeof AppToolsToolIdIndexRoute
  AppCharactersImportCardIdIndexRoute: typeof AppCharactersImportCardIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppActivityIndexRoute: AppActivityIndexRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppLorebooksIndexRoute: AppLorebooksIndexRoute,
  AppPersonasIndexRoute: AppPersonasIndexRoute,
  AppPresetsIndexRoute: AppPresetsIndexRoute,
  AppRegexesIndexRoute: AppRegexesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
  AppCharactersCharacterIdIndexRoute: AppCharactersCharacterIdIndexRoute,
  AppCharactersImportIndexRoute: AppCharactersImportIndexRoute,
  AppConnectionsConnectionIdIndexRoute: AppConnectionsConnectionIdIndexRoute,
  AppLorebooksLorebookIdIndexRoute: AppLorebooksLorebookIdIndexRoute,
  AppPersonasPersonaIdIndexRoute: AppPersonasPersonaIdIndexRoute,
  AppPresetsPresetIdIndexRoute: AppPresetsPresetIdIndexRoute,
  AppRegexesRegexIdIndexRoute: AppRegexesRegexIdIndexRoute,
  AppToolsToolIdIndexRoute: AppToolsToolIdIndexRoute,
  AppCharactersImportCardIdIndexRoute: AppCharactersImportCardIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ChatRouteRouteChildren {
  ChatChatsChatIdIndexRoute: typeof ChatChatsChatIdIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatChatsChatIdIndexRoute: ChatChatsChatIdIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface TwatterRouteRouteChildren {
  TwatterTwatterNotificationsRoute: typeof TwatterTwatterNotificationsRoute
  TwatterTwatterSearchRoute: typeof TwatterTwatterSearchRoute
  TwatterTwatterSettingsRoute: typeof TwatterTwatterSettingsRoute
  TwatterTwatterIndexRoute: typeof TwatterTwatterIndexRoute
  TwatterTwatterProfileAccountIdRoute: typeof TwatterTwatterProfileAccountIdRoute
  TwatterTwatterProfileIndexRoute: typeof TwatterTwatterProfileIndexRoute
}

const TwatterRouteRouteChildren: TwatterRouteRouteChildren = {
  TwatterTwatterNotificationsRoute: TwatterTwatterNotificationsRoute,
  TwatterTwatterSearchRoute: TwatterTwatterSearchRoute,
  TwatterTwatterSettingsRoute: TwatterTwatterSettingsRoute,
  TwatterTwatterIndexRoute: TwatterTwatterIndexRoute,
  TwatterTwatterProfileAccountIdRoute: TwatterTwatterProfileAccountIdRoute,
  TwatterTwatterProfileIndexRoute: TwatterTwatterProfileIndexRoute,
}

const TwatterRouteRouteWithChildren = TwatterRouteRoute._addFileChildren(
  TwatterRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  TwatterRouteRoute: TwatterRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
