export const CHAT_SUMMARY_OUTPUT_TOKENS = {
  DEFAULT: 4096,
  MIN: 256,
  MAX: 32768,
} as const;

export const DEFAULT_SUMMARY_RUN_INTERVAL = 5;
export const DEFAULT_SUMMARY_CONTEXT_SIZE = 50;
export const MAX_AUTOMATED_CHAT_SUMMARY_ENTRIES = 200;
