import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const repoRoot = path.resolve(__dirname, "../../..");
export const androidAppPkgRoot = path.resolve(__dirname, "..");
export const clientRoot = path.join(repoRoot, "apps", "client");
export const androidRoot = path.join(clientRoot, "android");
export const distRoot = path.join(androidAppPkgRoot, "dist");
export const packageJsonPath = path.join(androidAppPkgRoot, "package.json");

export function readPackage() {
  return JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
}

export function writePackage(pkg) {
  fs.writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf8");
}

/** Semver X.Y.Z → monotonic versionCode for Play/Android. */
export function versionCodeFromName(versionName) {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(versionName);
  if (!match) return 1;
  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);
  return major * 10000 + minor * 100 + patch;
}

export function bumpPatch(versionName) {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(versionName);
  if (!match) return "0.1.0";
  return `${match[1]}.${match[2]}.${Number(match[3]) + 1}`;
}

export function syncAndroidVersion(versionName) {
  const versionCode = versionCodeFromName(versionName);
  const propsPath = path.join(androidRoot, "app", "version.properties");
  const contents = [
    `# Generated by @ai-hub/android-app — do not edit by hand`,
    `versionName=${versionName}`,
    `versionCode=${versionCode}`,
    "",
  ].join("\n");
  fs.writeFileSync(propsPath, contents, "utf8");

  // Keep Capacitor widget version in sync when present.
  const configXml = path.join(
    androidRoot,
    "app",
    "src",
    "main",
    "res",
    "xml",
    "config.xml",
  );
  if (fs.existsSync(configXml)) {
    const xml = fs.readFileSync(configXml, "utf8");
    fs.writeFileSync(
      configXml,
      xml.replace(/version="[^"]*"/, `version="${versionName}"`),
      "utf8",
    );
  }

  return { versionName, versionCode };
}

export function apkDistName(versionName) {
  return `ai-hub-${versionName}.apk`;
}
